# Generated by Django 3.2.10 on 2022-01-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profession', models.CharField(max_length=250)),
                ('DateOfBirth', models.DateField()),
                ('webiste', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('freelancer', models.CharField(max_length=250)),
                ('desc', models.TextField(max_length=3000)),
                ('thumbnail', models.ImageField(upload_to='profile/')),
            ],
        ),
    ]
